[package]
name = "solana-geyser-plugin-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
agave-geyser-plugin-interface = { version = "=2.1.14" }
solana-logger = { version = "=2.1.14" }
log = "0.4.27"
